apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: nginx
    env: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      env: production
  template:
    metadata:
      labels:
        app: nginx
        env: production
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - prod
                      - devops
      containers:
        - name: web-app
          image: nginx
          ports:
            - containerPort: 80
