apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
spec:
  containers:
  - name: demo
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      touch /tmp/healthy;
      sleep 30;
      rm -f /tmp/healthy;
      sleep 3600;
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
