apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
spec:
  containers:
  - name: demo
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      sleep 30; touch /tmp/ready; sleep 3600
    readinessProbe:
      exec:
        command: ["cat", "/tmp/ready"]
      initialDelaySeconds: 5
      periodSeconds: 5
