apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    environment: production
spec:
  selector:
   # matchLabels:
    #  app: production
    matchExpressions:
#      - key: app
  #      operator: NotIn
   #     values: ["production", "prod"]
#       - key: app
 #        operator: In
  #       values: ["Development", "dev"]
#       - key: app
 #        operator: Exists
        - key: app
          operator: DoesNotExist
  template:
    metadata:
      name: temp-nginx
      labels:
        app: dev
    spec:
      volumes:
        - name: shared-date-logs
          emptyDir: {}
      containers:
        - name: container-writing-dates
          image: alpine
          command: ["/bin/sh", "-c"]
          args: ["while true; do date >> /usr/share/data/index.html; sleep 10; done"]
          volumeMounts:
            - name: shared-date-logs
              mountPath: /usr/share/data
        - name: container-serving-dates
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-date-logs
              mountPath: /usr/share/nginx/html
