apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prod-clusterrolebinding
subjects:
- kind: User
  name: produser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prod-clusterrole
  apiGroup: rbac.authorization.k8s.io
