apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: logging
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.19
          ports:
            - containerPort: 80
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
