apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "echo Hello Mahesh > /data/hello.txt && sleep 3600" ]
    volumeMounts:
    - name: my-storage
      mountPath: /data
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: demo-pvc
