apiVersion: v1
kind: Namespace
metadata:
  name: mern-app
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: mern-app
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9zbWFoZXNoLWt1bWFycjpNYWhlc2hLdW1hckBjbHVzdGVyMC50bHNidS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAvZGV2b3BzLXBpcGVsaW5lLW1hbmFnZXI=
  JWT_SECRET: ZGV2b3BzLXBpcGVsaW5lLW1hbmFnZXItc2VjcmV0LWtleS0yMDI0
  FRONTEND_ORIGIN: aHR0cDovLzEwLjI0Ny4xMDUuNTg6MzAwMDE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: maheshkumars772/cicd-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://10.247.105.58:30002/api"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: maheshkumars772/cicd-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "development"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: FRONTEND_ORIGIN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FRONTEND_ORIGIN
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
  type: NodePort
