apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-writing-dates
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"]
    volumeMounts:
    - name: shared-date-logs
      mountPath: /var/log
  - name: container-serving-dates
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-date-logs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-date-logs
    emptyDir:
      sizeLimit: 500Mi
      medium: Memory
