apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32100 #incase apps need to choose a speicf server 
  type: NodePort    # type not needed when ClusterIP
