apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None  # This is required for StatefulSet to expose each pod with its stable DNS name
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: web
