---
apiVersion: v1
kind: Pod
metadata:
  name: demo123
  labels:
    env: prod
spec:
  containers:
    - name: custom-nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
          name: http
          protocol: TCP

