apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
  labels:
    app: nginx
spec:
  replicas: 3
  selector:  
    matchLabels:
      app: nginx
  template:  
    metadata:
      labels:
        app: nginx
    spec:  
      containers:
      - name: nginx-container
        image: maheshkumars772/nginx
        ports:
        - containerPort: 80
