apiVersion: v1
kind: Secret
metadata:
  name: nginx-date
type: Opaque
data:
  username: bXJfX2t1bWFyX18wMDYK
  password: bWFoZXNoa3VtYXJzNzcy
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-test-pod
# spec:
#   containers:
#     - name: test-container
#       image: nginx
#       env:
#         - name: USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: nginx-date
#               key: username
#         - name: PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: nginx-date
#               key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      envFrom:
        - secretRef:
            name: nginx-date

