apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bWFoZXNoa3VtYXJzNzcy
  password: bXJfX2t1bWFyX18wMDYK

--- 

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
